import 'dart:async';
import 'dart:js_interop';
import 'dart:typed_data';

import 'package:web/web.dart' as web;

/// Downloads the already-generated bytes directly, instead of asking the PDF
/// preview to regenerate the document during a browser gesture. This avoids
/// the blank-file issue observed on web browsers.
Future<void> downloadPdf(Uint8List bytes, String filename) async {
  final file = web.Blob(
    [bytes.toJS].toJS,
    web.BlobPropertyBag(type: 'application/pdf'),
  );
  final objectUrl = web.URL.createObjectURL(file);
  final link = web.HTMLAnchorElement()
    ..href = objectUrl
    ..download = filename
    ..style.display = 'none';
  web.document.body?.append(link);
  link.click();
  link.remove();

  // The browser starts reading the Blob asynchronously. Revoking it too soon
  // can produce an empty file, so only release it after that hand-off.
  await Future<void>.delayed(const Duration(seconds: 2));
  web.URL.revokeObjectURL(objectUrl);
}
