import 'dart:typed_data';

export 'pdf_download_service_stub.dart'
    if (dart.library.js_interop) 'pdf_download_service_web.dart';

/// Shared validation for every PDF export path.
///
/// The preview package can display a document while a browser download is
/// still pending. Checking the generated bytes before offering a save action
/// prevents a zero-byte or otherwise invalid attachment from being exported.
bool isUsablePdf(Uint8List bytes) {
  if (bytes.length < 1024) return false;
  const signature = <int>[0x25, 0x50, 0x44, 0x46, 0x2d]; // %PDF-
  for (var index = 0; index < signature.length; index++) {
    if (bytes[index] != signature[index]) return false;
  }
  return true;
}
