org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=768M -XX:ReservedCodeCacheSize=192m -Xss512k -XX:ActiveProcessorCount=2 -XX:HeapBaseMinAddress=32g -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
