-- Werkly MVP schema. Apply from the Supabase SQL editor or CLI.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  university text not null default '',
  degree text not null default '',
  city text not null default 'München',
  professional_summary text not null default '',
  skills jsonb not null default '[]'::jsonb,
  preferences jsonb not null default '{}'::jsonb,
  cv_path text,
  profile_completion integer not null default 20 check (profile_completion between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  external_id text not null,
  title text not null,
  company text not null,
  location text not null,
  latitude double precision,
  longitude double precision,
  remote_type text not null default 'onsite' check (remote_type in ('onsite', 'hybrid', 'remote')),
  salary_min numeric,
  salary_max numeric,
  currency text not null default 'EUR',
  source text not null,
  source_url text not null,
  tags text[] not null default '{}',
  description text not null default '',
  posted_at timestamptz not null default now(),
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (source, external_id)
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, job_id)
);

create table if not exists public.applications (
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  status text not null default 'preparing' check (status in ('preparing', 'applied', 'interview', 'offer', 'rejected')),
  notes text not null default '',
  applied_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, job_id)
);

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.favorites enable row level security;
alter table public.applications enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "jobs_read_active" on public.jobs;
create policy "jobs_read_active" on public.jobs for select using (active = true);
drop policy if exists "favorites_manage_own" on public.favorites;
create policy "favorites_manage_own" on public.favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "applications_manage_own" on public.applications;
create policy "applications_manage_own" on public.applications for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('cvs', 'cvs', false, 10485760, array['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "cv_read_own" on storage.objects;
create policy "cv_read_own" on storage.objects for select to authenticated
using (bucket_id = 'cvs' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "cv_insert_own" on storage.objects;
create policy "cv_insert_own" on storage.objects for insert to authenticated
with check (bucket_id = 'cvs' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "cv_update_own" on storage.objects;
create policy "cv_update_own" on storage.objects for update to authenticated
using (bucket_id = 'cvs' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "cv_delete_own" on storage.objects;
create policy "cv_delete_own" on storage.objects for delete to authenticated
using (bucket_id = 'cvs' and (storage.foldername(name))[1] = auth.uid()::text);

insert into public.jobs (id, external_id, title, company, location, latitude, longitude, remote_type, salary_min, salary_max, source, source_url, tags, description, posted_at)
values
  (1, 'demo-celonis-data', 'Werkstudent Data Analytics', 'Celonis', 'München · Maxvorstadt', 48.1510, 11.5700, 'onsite', 16, 19, 'LinkedIn', 'https://www.linkedin.com/jobs/', array['Python','SQL','Power BI'], 'Aide l’équipe Customer Value à transformer des données complexes en analyses claires et actionnables.', now() - interval '2 hours'),
  (2, 'demo-personio-ai', 'Working Student — AI Product', 'Personio', 'München · Altstadt', 48.1374, 11.5755, 'hybrid', 17, 20, 'StepStone', 'https://www.stepstone.de/', array['Product','LLM','Figma'], 'Contribue à des fonctionnalités IA, de la recherche utilisateur au suivi des expérimentations produit.', now() - interval '1 day'),
  (3, 'demo-siemens-flutter', 'Werkstudent Software Engineering', 'Siemens', 'München · Perlach', 48.1000, 11.6300, 'hybrid', 15, 18, 'Indeed', 'https://de.indeed.com/', array['Flutter','REST API','Git'], 'Développe des interfaces mobiles pour les équipes industrielles dans une squad internationale.', now() - interval '2 days'),
  (4, 'demo-allianz-bi', 'Werkstudent Business Intelligence', 'Allianz', 'Unterföhring', 48.1910, 11.6460, 'onsite', 16, 18, 'LinkedIn', 'https://www.linkedin.com/jobs/', array['Excel','Tableau','English'], 'Crée des dashboards pour piloter la performance et automatise la préparation des reportings.', now() - interval '3 days'),
  (5, 'demo-flix-ux', 'Working Student UX Research', 'Flix', 'München · Hackerbrücke', 48.1420, 11.5480, 'onsite', 15, 17, 'Indeed', 'https://de.indeed.com/', array['Research','Figma','Deutsch'], 'Prépare les tests utilisateurs et transforme les retours voyageurs en recommandations produit.', now() - interval '4 days')
on conflict (id) do update set
  title = excluded.title,
  company = excluded.company,
  location = excluded.location,
  tags = excluded.tags,
  description = excluded.description,
  active = true;

select setval(pg_get_serial_sequence('public.jobs', 'id'), greatest((select max(id) from public.jobs), 1));
