create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature text not null check (feature in ('assistant', 'cv_analysis')),
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_events_user_feature_created_idx
  on public.ai_usage_events (user_id, feature, created_at desc);

alter table public.ai_usage_events enable row level security;
revoke all on public.ai_usage_events from public, anon, authenticated;
grant all on public.ai_usage_events to service_role;

comment on table public.ai_usage_events is
  'Server-only counters used to protect the free AI quota. No prompts or CV content are stored.';
